### ISSUE TITLE
why :Couldn't match files for checkpoint checkpoints\FCN_epoch_29.ckpt Please train model first !!! ERROR:tensorflow:Couldn't match files for checkpoint checkpoints\FCN_epoch_29.ckpt Traceback (most recent call last):

### ISSUE THREAD

**Issue by zhangyuboshengdan** [OnionDoctor/FCN_for_crack_recognition#1]
RESTART: C:\Users\zhangyubo\Desktop\FCN_for_crack_recognition-master (1)\FCN_finetune.py 

Warning (from warnings module):
  File "C:\Users\zhangyubo\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py", line 36
    from ._conv import register_converters as _register_converters
FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>>> Setting up FCN model ...
WARNING:tensorflow:From C:\Users\zhangyubo\Desktop\FCN_for_crack_recognition-master (1)\FCN_model.py:123: calling argmax (from tensorflow.python.ops.math_ops) with dimension is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
>>> Setting up FCN summary ...
>>> Setting up FCN writer and saver ...
>>> Loading images from test directory ...
ERROR:tensorflow:Couldn't match files for checkpoint checkpoints\FCN_epoch_29.ckpt
Please train model first !!!
ERROR:tensorflow:Couldn't match files for checkpoint checkpoints\FCN_epoch_29.ckpt
Traceback (most recent call last):
  File "C:\Users\zhangyubo\Desktop\FCN_for_crack_recognition-master (1)\FCN_finetune.py", line 215, in <module>
    tf.app.run()
  File "C:\Users\zhangyubo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "C:\Users\zhangyubo\Desktop\FCN_for_crack_recognition-master (1)\FCN_finetune.py", line 182, in main
    saver.restore(sess, tf.train.latest_checkpoint(FLAGS.checkpoint_dir))
  File "C:\Users\zhangyubo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1751, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by hb478858102** [comment]
I have the same problem, have you solved it?

**Comment by gaoyumin11** [comment]
me too，do you know how to solve it
