### ISSUE TITLE
ValueError: setting an array element with a sequence after training the first 310 batches of first epoch

### ISSUE THREAD

**Issue by nys09** [OnionDoctor/FCN_for_crack_recognition#8]
I am trying to train the network with the dataset provided. After running the first 310 batches of the first epoch as shown below, I am getting an error. Kindly help me debug this.

Epoch: [0 / 20] Batch: [304 / 310] Loss: 0.084585, Time: 3.997 sec
Epoch: [0 / 20] Batch: [305 / 310] Loss: 0.231262, Time: 4.030 sec
Epoch: [0 / 20] Batch: [306 / 310] Loss: 0.063675, Time: 4.021 sec
Epoch: [0 / 20] Batch: [307 / 310] Loss: 0.041127, Time: 4.010 sec
Epoch: [0 / 20] Batch: [308 / 310] Loss: 0.083826, Time: 4.079 sec
Epoch: [0 / 20] Batch: [309 / 310] Loss: 0.131809, Time: 4.030 sec
Traceback (most recent call last):
  File "FCN_finetune.py", line 215, in <module>
    tf.app.run()
  File "C:\Users\Yeshwanth Sai Neeli\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "FCN_finetune.py", line 146, in main
    feed_dict={img_holder: batch_img_, ant_holder: batch_ant_})
  File "C:\Users\Yeshwanth Sai Neeli\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\Yeshwanth Sai Neeli\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "C:\Users\Yeshwanth Sai Neeli\Anaconda3\lib\site-packages\numpy\core\numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)
**ValueError: setting an array element with a sequence.**

**Comment by jianzhang96** [comment]
me too. I got this error at the beginning of training.

**Comment by youngkang9998** [comment]
+1.  I got the same error at the beginning of training.

**Comment by Dante-M1028** [comment]
Me too. Have all of you solved this problem?

**Comment by jianzhang96** [comment]
For me, I have solved  it. First, I ran the code on MacOS and got this error. Then, I ran it on Windows and the error disappeared. Therefore I guess the error is caused by OS difference. the line break in .txt file in MacOS is '\n', and however in Windows is '\r\n'. I checked that in train.txt and valid.txt and solved the problem. May be helpful to you. :)

**Comment by wst1234e** [comment]
May I ask if this problem has been solved, and I have encountered the same problem.

**Comment by wst1234e** [comment]
> 对我来说，我已经解决了。首先，我在 MacOS 上运行代码并弄错了。然后，我在 Windows 上运行它，错误消失了。因此，我想错误是由操作系统差异引起的。MacOS 中.txt文件中的行中断是"\n"，然而在 Windows 中是"\n"。n"。我在火车上检查了.txt和有效.txt并解决了问题。可能对你有帮助。:)

Which version of windows are you using, please?
